stages:
  - deploy

# deploy_frontend:
#   stage: deploy
#   only:
#     - master
#   tags:
#     - TG-ABDU-2

#   before_script:
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

#   script:
#     - echo "Building Docker image..."

#     # ✅ PASS API URL DURING BUILD (ONE LINE)
#     - docker build --build-arg NEXT_PUBLIC_API_URL=http://10.57.23.109:8004/v1 -t telegram-bot-front .

#     - echo "Saving image..."
#     - docker save telegram-bot-front | gzip > telegram-bot-front.tar.gz

#     - echo "Copying image to server..."
#     - scp telegram-bot-front.tar.gz $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/

#     - echo "Deploying on server..."
#     - |
#       ssh $SERVER_USER@$SERVER_IP << EOF
#         docker network create tg-dns || true
        
#         docker load < telegram-bot-front.tar.gz
#         docker stop telegram-bot-front || true
#         docker rm -f telegram-bot-front || true

#         docker run -d \
#           --name telegram-bot-front \
#           -p 4005:4005 \
#           --restart unless-stopped \
#           --network tg-dns \
#           telegram-bot-front
#       EOF

deploy_frontend_windows:
  stage: deploy
  only:
    - master
  tags:
    - TG-ABDU-4

  script:
    - echo "Deploying Next.js frontend on Windows server..."
    - cd C:\Users\Admin\Documents\TG-referral-bot\telegram-bot-front

    - echo "Pulling latest code..."
    - git pull origin master

    - echo "Installing node modules..."
    - npm install

    - echo "Building Next.js project..."
    - npm run build

    - echo "Setting PM2 home to avoid permission issues..."
    - $env:PM2_HOME = "C:\Users\Admin\.pm2"

    - echo "Restarting frontend cleanly with PM2..."
    - |
        $ErrorActionPreference = "SilentlyContinue"

        cmd /c "pm2 delete telegram-bot-front" | Out-Null
        cmd /c "pm2 start npm --name telegram-bot-front -- start"
        cmd /c "pm2 save"

        exit 0